hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  launcher:
    _target_: hydra._internal.core_plugins.basic_launcher.BasicLauncher
  sweeper:
    _target_: hydra._internal.core_plugins.basic_sweeper.BasicSweeper
    max_batch_size: null
    params: null
  help:
    app_name: ${hydra.job.name}
    header: '${hydra.help.app_name} is powered by Hydra.

      '
    footer: 'Powered by Hydra (https://hydra.cc)

      Use --hydra-help to view Hydra specific help

      '
    template: '${hydra.help.header}

      == Configuration groups ==

      Compose your configuration from those groups (group=option)


      $APP_CONFIG_GROUPS


      == Config ==

      Override anything in the config (foo.bar=value)


      $CONFIG


      ${hydra.help.footer}

      '
  hydra_help:
    template: 'Hydra (${hydra.runtime.version})

      See https://hydra.cc for more info.


      == Flags ==

      $FLAGS_HELP


      == Configuration groups ==

      Compose your configuration from those groups (For example, append hydra/job_logging=disabled
      to command line)


      $HYDRA_CONFIG_GROUPS


      Use ''--cfg hydra'' to Show the Hydra config.

      '
    hydra_help: ???
  hydra_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][HYDRA] %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
    root:
      level: INFO
      handlers:
      - console
    loggers:
      logging_example:
        level: DEBUG
    disable_existing_loggers: false
  job_logging:
    version: 1
    formatters:
      simple:
        format: '[%(asctime)s][%(name)s][%(levelname)s] - %(message)s'
    handlers:
      console:
        class: logging.StreamHandler
        formatter: simple
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        formatter: simple
        filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log
    root:
      level: INFO
      handlers:
      - console
      - file
    disable_existing_loggers: false
  env: {}
  mode: MULTIRUN
  searchpath: []
  callbacks: {}
  output_subdir: .hydra
  overrides:
    hydra:
    - hydra.mode=MULTIRUN
    task:
    - trial=1,2
    - poisoning.method=blurring
    - poisoning.target_cids=[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6],[0,1,2,3],[0]
    - poisoning.rate=0.05,0.15,0.3
  job:
    name: server
    chdir: null
    override_dirname: poisoning.method=blurring,poisoning.rate=0.05,0.15,0.3,poisoning.target_cids=[0,1,2,3,4,5,6,7,8,9],[0,1,2,3,4,5,6],[0,1,2,3],[0],trial=1,2
    id: ???
    num: ???
    config_name: antivenom
    env_set: {}
    env_copy: []
    config:
      override_dirname:
        kv_sep: '='
        item_sep: ','
        exclude_keys: []
  runtime:
    version: 1.3.2
    version_base: '1.3'
    cwd: /home/user/kuchida/master_thesis/fl_on_raspberryPI
    config_sources:
    - path: hydra.conf
      schema: pkg
      provider: hydra
    - path: /home/user/kuchida/master_thesis/fl_on_raspberryPI/conf
      schema: file
      provider: main
    - path: ''
      schema: structured
      provider: schema
    output_dir: ???
    choices:
      hydra/env: default
      hydra/callbacks: null
      hydra/job_logging: default
      hydra/hydra_logging: default
      hydra/hydra_help: default
      hydra/help: default
      hydra/sweeper: basic
      hydra/launcher: basic
      hydra/output: default
  verbose: false
num_clients: 10
num_epochs: 5
num_rounds: 50
server_address: 192.168.0.110:7777
seed: 1234
trial: 1
client:
  cid: 0
dataset:
  dataset_name: trashnet
  partition_type: uniform
  dirichlet_alpha: 0.1
  batch_size:
    train: 16
    test: 16
  shuffle:
    train: true
    test: false
  testset_size: 0.2
poisoning:
  is_enabled: true
  method: blurring
  rate: 0.05
  target_cids:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
optim_scheduler:
  scheduler: adam
  lr: 0.0005
  momentum: 0.9
strategy:
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 10
  min_evaluate_clients: 10
  min_available_clients: 10
directory:
  log: ./log
  figure: ./figure
  datasets: ./datasets
  loaders: ./loaders
mlflow:
  exname: antivenom
