server_address: '192.168.0.110:5555'
num_clients: 10
num_epochs: 5
num_rounds: 10
seed: 0

control:
  model_split_mode: 'fix'
  model_mode: 'a1-b1-c1-d1-e1'
  cpu_scores: [1000, 1000, 1000, 1000, 1000, 500, 500, 500, 250, 250] # only used in case of based_on_cpu 
  manual_model_rate: [1.0, 1.0, 0.5, 0.5, 0.25, 0.25, 0.125, 0.125, 0.0625, 0.0625]

dataset:
  dataset_name: 'CIFAR10'
  iid: true
  shard_per_user : 2 # only used in case of non-iid (i.e. iid = false)
  balance: false
  batch_size:
    train: 10
    test: 50
  shuffle:
    train: true
    test: false


model:
  model_name: resnet18  # use 'conv' for MNIST
  hidden_layers: [64 , 128 , 256 , 512]
  norm: bn
  scale: 1
  mask: 1


optim_scheduler:
  optimizer: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 5.00e-04
  scheduler: MultiStepLR
  milestones: [300, 500]

strategy:
  _target_: heterofl.strategy.HeteroFL
  fraction_fit: 1.0
  fraction_evaluate: 1.0
  min_fit_clients: 10
  min_evaluate_clients: 10

mlflow:
  exname: tutorial_cifar
